[package]
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
categories = ["database", "data-structures"]
description = "An ODM for MongoDB built upon the mongo rust driver."
documentation = "https://github.com/thedodd/wither"
exclude = []
homepage = "https://github.com/thedodd/wither"
keywords = ["mongodb", "odm", "orm"]
license = "Apache-2.0"
name = "wither_derive"
readme = "../README.md"
repository = "https://github.com/thedodd/wither"
version = "0.6.0"

[lib]
proc-macro = true

[dependencies]
bson = "0.12"
Inflector = "0.11"
mongodb = "0.3"
proc-macro2 = "0.4"
quote = "0.6"
serde = "1"
syn = { version = "0.15", features = ["extra-traits"] }

[features]
docinclude = [] # Used only for activating `doc(include="...")` on stable.

[package.metadata.docs.rs]
features = ["docinclude"] # Activate `docinclude` during docs.rs build.
