version: '2'
services:
  _base:
    build: .
    command: cargo test -p wither --tests --lib -- --test-threads=1
    working_dir: /wither

  test.3-2:
    extends:
      service: _base
    links:
      - mongodb.3-2
    environment:
      BACKEND_HOST: mongodb.3-2
      BACKEND_PORT: 27017

  test.3-4:
    extends:
      service: _base
    links:
      - mongodb.3-4
    environment:
      BACKEND_HOST: mongodb.3-4
      BACKEND_PORT: 27017

  test.3-6:
    extends:
      service: _base
    links:
      - mongodb.3-6
    environment:
      BACKEND_HOST: mongodb.3-6
      BACKEND_PORT: 27017

  test.4-0:
    extends:
      service: _base
    links:
      - mongodb.4-0
    environment:
      BACKEND_HOST: mongodb.4-0
      BACKEND_PORT: 27017

  test.with-mounts:
    extends:
      service: _base
    command: bash -c 'cargo install cargo-watch && cargo watch -s "cargo test --lib --tests"'
    depends_on:
      - mongodb.3-6
    environment:
      BACKEND_HOST: mongodb.3-6
      BACKEND_PORT: 27017
    volumes:
      - ./Cargo.lock:/wither/Cargo.lock
      - ./Cargo.toml:/wither/Cargo.toml
      - ./wither:/wither/wither
      - ./wither_derive:/wither/wither_derive

  mongodb.3-2:
    image: mongo:3.2
    ports:
      - 27017

  mongodb.3-4:
    image: mongo:3.4
    ports:
      - 27017

  mongodb.3-6:
    image: mongo:3.6
    ports:
      - 27017

  mongodb.4-0:
    image: mongo:4.0-rc
    ports:
      - 27017
